services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
      - mongodb:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - db

volumes:
  mongodb:

networks:
  db:
    driver: bridge