name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  tests-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps
      - working-directory: ./api
      - run: yarn install
      - name: Tests api
      - working-directory: ./api
      - run: yarn install
